/*
 * GovIO API
 * # Warning **This is an experimental API that is (most probably) going to change as we evolve the IO platform.** # Introduction This is the documentation of the GovIO API for 3rd party services. This API enables Public Administration services to send messages directly to citiziens through the  IO platform in a simple and templatized way.    
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.govhub.govio.planner.batch.bean;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets FileStatus
 */
public enum FileStatus {
  
  CREATED("created"),
  
  PROCESSING("processing"),
  
  PROCESSED("processed");

  private String value;

  FileStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static FileStatus fromValue(String value) {
    for (FileStatus b : FileStatus.values()) {
      if (b.value.equalsIgnoreCase(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

